// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dxuxjwfaqdmjytpxglru.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImR4dXhqd2ZhcWRtanl0cHhnbHJ1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjA4Nzg5NTMsImV4cCI6MjA3NjQ1NDk1M30.All17AAHz1Xt_H_J5K6Zem_MBG87dJgdlbpJgHZOgpE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});